<script setup>
import { computed, onMounted } from 'vue'
import { useContentStore } from '../stores/contentStore'
const contentStore = useContentStore()
const about = computed(() => contentStore.aboutPage)
const sections = computed(() => [...(about.value.sections || [])].filter((s) => s.active !== false).sort((a,b)=>Number(a.sortOrder||0)-Number(b.sortOrder||0)))
onMounted(() => contentStore.loadStorefrontContent())
</script>
<template>
  <main class="min-h-screen bg-black text-white">
    <section class="relative overflow-hidden border-b border-white/10 bg-[#050607]"><div class="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(229,9,20,0.12),transparent_34%),radial-gradient(circle_at_15%_80%,rgba(255,255,255,0.07),transparent_32%)]"></div><p class="pointer-events-none absolute left-1/2 top-1/2 hidden -translate-x-1/2 -translate-y-1/2 text-[clamp(8rem,19vw,20rem)] font-black uppercase leading-none tracking-[-0.09em] text-white/[0.035] lg:block">{{ about.hero?.backgroundWord || 'HAXON' }}</p><div class="relative mx-auto max-w-[1500px] px-5 py-16 sm:px-8 lg:px-12"><div class="max-w-4xl"><div class="mb-6 h-1 w-10 bg-[#E50914] shadow-[0_0_18px_rgba(229,9,20,.7)]"></div><p class="text-[11px] font-black uppercase tracking-[0.32em] text-white/45">{{ about.hero?.eyebrow }}</p><h1 class="mt-5 text-[clamp(3.1rem,7vw,7.5rem)] font-black uppercase leading-[0.84] tracking-[-0.075em]">{{ about.hero?.title }}</h1><p class="mt-7 max-w-2xl text-base leading-8 text-white/55 sm:text-lg">{{ about.hero?.subtitle }}</p></div></div></section>
    <section class="mx-auto max-w-[1500px] px-5 py-12 sm:px-8 lg:px-12"><div class="grid gap-6"><article v-for="(section, index) in sections" :key="section.id || index" class="border border-white/10 bg-[#050607] p-7 sm:p-9" :class="section.type === 'quote' ? 'lg:ml-auto lg:w-2/3' : ''"><p class="text-[10px] font-black uppercase tracking-[0.28em] text-[#E50914]">{{ section.eyebrow || String(index + 1).padStart(2, '0') }}</p><blockquote v-if="section.type === 'quote'" class="mt-5 text-[clamp(2rem,4vw,4.7rem)] font-light leading-[1.05] tracking-[-0.055em] text-white/90">“{{ section.quote || section.body }}”<footer class="mt-6 text-sm font-black uppercase tracking-[.18em] text-white/35">{{ section.attribution }}</footer></blockquote><template v-else><h2 class="mt-5 text-[clamp(2.3rem,5vw,5.5rem)] font-black uppercase leading-[0.88] tracking-[-0.06em]">{{ section.title }}</h2><p class="mt-7 max-w-3xl text-base leading-8 text-white/52">{{ section.body }}</p></template></article></div><div v-if="about.cta?.active !== false" class="mt-8 border border-[#E50914]/35 bg-[#E50914]/10 p-8"><h2 class="text-3xl font-black uppercase tracking-[-.04em]">{{ about.cta?.title }}</h2><p class="mt-4 max-w-2xl text-white/60">{{ about.cta?.body }}</p><router-link :to="about.cta?.link || '/products'" class="mt-6 inline-flex border border-white/15 px-6 py-4 text-[11px] font-black uppercase tracking-[.16em] hover:border-[#E50914]">{{ about.cta?.label || 'Shop now' }} →</router-link></div></section>
  </main>
</template>
