<script setup>
import { computed, onMounted, ref } from 'vue'
import { collection, getDocs, orderBy, query } from 'firebase/firestore'
import { db } from '../firebase/config'
import HaxonImage from '../components/ui/HaxonImage.vue'
import { useSeo } from '../composables/useSeo'
const fallbackCatalogs = [{ name: 'Haxon Lighting Selection', slug: 'lighting-selection', brand: 'Haxon', category: 'LED & Lighting', thumbnail: '/image/products/no-image.jpeg', pdfUrl: '#', description: 'Downloadable catalog placeholder. Add Firestore catalogs to replace this fallback.', active: true, sortOrder: 1 }]
const catalogs = ref(fallbackCatalogs); const loading = ref(true); const error = ref(''); const filter = ref('All')
const categories = computed(() => ['All', ...new Set(catalogs.value.map((c) => c.category).filter(Boolean))])
const visible = computed(() => catalogs.value.filter((c) => c.active !== false && (filter.value === 'All' || c.category === filter.value)))
onMounted(async () => { useSeo({ title: 'Catalogs', description: 'Download Haxon product catalogs, brand PDFs, manuals and selection guides.' }); try { const snap = await getDocs(query(collection(db, 'catalogs'), orderBy('sortOrder', 'asc'))); const data = snap.docs.map((d) => ({ id: d.id, ...d.data() })); if (data.length) catalogs.value = data } catch(e) { error.value = 'Unable to load live catalogs. Showing fallback catalog data.' } finally { loading.value = false } })
</script>
<template>
  <main class="min-h-screen bg-black pt-[74px] text-white"><section class="border-b border-white/10 bg-[#050607]"><div class="mx-auto max-w-[1500px] px-5 py-14 sm:px-8 lg:px-12"><p class="text-[11px] font-black uppercase tracking-[0.3em] text-white/45">Downloads</p><h1 class="mt-4 text-[clamp(3rem,8vw,7rem)] font-black uppercase leading-none tracking-[-0.075em]">Catalogs.</h1><p class="mt-6 max-w-2xl text-white/55">Brand catalogs, manuals and PDFs managed from Firebase.</p></div></section><section class="mx-auto max-w-[1500px] px-5 py-10 sm:px-8 lg:px-12"><div class="mb-6 flex items-center justify-between"><select v-model="filter" class="border border-white/10 bg-black px-4 py-3 text-sm"><option v-for="item in categories" :key="item">{{ item }}</option></select><p class="text-sm text-white/40">{{ visible.length }} catalogs</p></div><p v-if="error" class="mb-5 border border-amber-400/20 bg-amber-400/10 p-4 text-sm text-amber-100">{{ error }}</p><div v-if="loading" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div v-for="n in 4" :key="n" class="h-72 animate-pulse border border-white/10 bg-white/5"></div></div><div v-else class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article v-for="catalog in visible" :key="catalog.id || catalog.slug" class="border border-white/10 bg-[#050607]"><HaxonImage :src="catalog.thumbnail" :alt="catalog.name" ratio="aspect-[4/3]" fit="cover" /><div class="p-5"><p class="text-[10px] font-black uppercase tracking-[0.18em] text-[#E50914]">{{ catalog.brand }} · {{ catalog.category }}</p><h2 class="mt-3 text-xl font-black uppercase tracking-[-0.04em]">{{ catalog.name }}</h2><p class="mt-3 line-clamp-2 text-sm leading-6 text-white/50">{{ catalog.description }}</p><a :href="catalog.pdfUrl" target="_blank" class="mt-5 grid h-11 place-items-center border border-white/10 text-[10px] font-black uppercase tracking-[0.16em] text-white/70 hover:bg-white hover:text-black">Open PDF</a></div></article></div></section></main>
</template>
