<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { db } from '../firebase/config'
import { useCartStore } from '../stores/cartStore'
import { buildTimelineEntry, formatPrice, normalizePhone, productImage, productMode } from '../lib/catalog'
const router=useRouter(); const cart=useCartStore(); const loading=ref(false); const success=ref('')
const form=ref({ name:'', phone:'', email:'', address:'', city:'', notes:'', paymentMethod:'Cash on Delivery' })
const delivery=ref(0); const subtotal=computed(()=>cart.items.reduce((s,i)=>s+Number(i.salePrice||i.price||0)*Number(i.quantity||1),0)); const total=computed(()=>subtotal.value+Number(delivery.value||0))
const needsConfirmation=computed(()=>cart.items.some(i=>['Confirm Fitment','On Request','Premium Import'].includes(productMode(i))))
const orderNumber=()=>`HXN-${new Date().getFullYear()}-${Math.floor(100000+Math.random()*900000)}`
const place=async()=>{ if(!cart.items.length || !form.value.name || !form.value.phone || !form.value.address || !form.value.city) return; loading.value=true; const number=orderNumber(); try{ const items=cart.items.map(i=>({ id:i.id,name:i.name,brand:i.brand||i.carBrand||'',category:i.category||'',image:productImage(i),price:Number(i.salePrice||i.price||0),quantity:Number(i.quantity||1),productMode:productMode(i),fitmentNotes:i.fitmentNotes||'' })); await addDoc(collection(db,'orders'),{ orderNumber:number, customer:{ name:form.value.name, phone:form.value.phone, normalizedPhone:normalizePhone(form.value.phone), email:form.value.email, address:form.value.address, city:form.value.city }, customerName:form.value.name, phone:form.value.phone, normalizedPhone:normalizePhone(form.value.phone), email:form.value.email, address:form.value.address, city:form.value.city, items, products:items, subtotal:subtotal.value, deliveryCharges:Number(delivery.value||0), delivery:Number(delivery.value||0), discount:0, customAdjustment:0, total:total.value, totalAmount:total.value, paymentMethod:form.value.paymentMethod, paymentStatus:'Unpaid', orderStatus:'Pending', status:'Pending', notes:form.value.notes, adminNotes:'', timeline:[buildTimelineEntry('Pending','Order received by Haxon')], requiresFitmentConfirmation:needsConfirmation.value, createdAt:serverTimestamp(), updatedAt:serverTimestamp() }); cart.clearCart(); success.value=number } finally{ loading.value=false } }
</script>
<template><div class="min-h-screen bg-[#0B0D10] px-6 py-16 text-[#F5F5F2]"><div class="mx-auto max-w-7xl"><h1 class="text-5xl font-black">Checkout.</h1><div v-if="success" class="mt-8 rounded-[2rem] border border-emerald-300/30 bg-emerald-300/10 p-8"><h2 class="text-3xl font-black">Order placed: {{ success }}</h2><p class="mt-3 text-[#A5A7AA]">Haxon will confirm availability, fitment, and payment details before dispatch.</p><router-link to="/track-order" class="mt-6 inline-block rounded-full bg-white px-6 py-3 font-bold text-[#0B0D10]">Track order</router-link></div><div v-else-if="cart.items.length" class="mt-8 grid gap-8 lg:grid-cols-3"><div class="lg:col-span-2 rounded-[2rem] border border-white/10 bg-[#11151B] p-6"><div class="grid gap-4 md:grid-cols-2"><input v-model="form.name" placeholder="Full name *" class="input"/><input v-model="form.phone" placeholder="Phone *" class="input"/><input v-model="form.email" placeholder="Email" class="input"/><input v-model="form.city" placeholder="City *" class="input"/><textarea v-model="form.address" placeholder="Address *" class="input md:col-span-2"></textarea><textarea v-model="form.notes" placeholder="Notes / vehicle details" class="input md:col-span-2"></textarea><select v-model="form.paymentMethod" class="input md:col-span-2"><option>Cash on Delivery</option><option>Bank Transfer</option><option>Easypaisa/JazzCash placeholder</option></select></div><p v-if="needsConfirmation" class="mt-5 rounded-2xl border border-amber-300/30 bg-amber-300/10 p-4 text-amber-100">Some products require fitment/price confirmation before final dispatch.</p></div><aside class="rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><h2 class="text-2xl font-black">Order summary</h2><div v-for="item in cart.items" :key="item.id" class="mt-5 flex gap-3"><img :src="productImage(item)" class="h-16 w-16 rounded-xl object-cover"/><div><p class="font-bold">{{ item.name }}</p><p class="text-sm text-[#A5A7AA]">{{ item.quantity }} × {{ formatPrice(item.salePrice || item.price) }}</p></div></div><div class="mt-6 space-y-2 border-t border-white/10 pt-5"><p class="flex justify-between"><span>Subtotal</span><b>{{ formatPrice(subtotal) }}</b></p><p class="flex justify-between"><span>Delivery</span><b>{{ formatPrice(delivery) }}</b></p><p class="flex justify-between text-2xl"><span>Total</span><b>{{ formatPrice(total) }}</b></p></div><button class="mt-6 w-full rounded-full bg-white py-4 font-bold uppercase tracking-[.16em] text-[#0B0D10]" @click="place">{{ loading ? 'Placing...' : 'Place order' }}</button></aside></div><div v-else class="mt-8 rounded-[2rem] border border-white/10 p-12 text-center"><h2 class="text-3xl font-black">Your cart is empty.</h2><router-link to="/products" class="mt-6 inline-block rounded-full bg-white px-6 py-3 font-bold text-[#0B0D10]">Shop products</router-link></div></div></div></template>
<style scoped>.input{border-radius:1rem;border:1px solid rgba(255,255,255,.1);background:#0B0D10;padding:1rem;color:white;outline:none}.input:focus{border-color:rgba(207,250,254,.4)}</style>
