<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { useProductStore } from '../stores/productStore'
import { useCartStore } from '../stores/cartStore'
import ProductCard from '../components/ui/ProductCard.vue'
import { FALLBACK_IMAGE, formatPrice, productBrand, productImage, productMode } from '../lib/catalog'
const route = useRoute(); const store = useProductStore(); const cart = useCartStore(); const selected = ref('')
onMounted(async()=>{ if(!store.products.length) await store.fetchProducts(); selected.value = productImage(product.value) })
const product = computed(()=> store.products.find((p)=> p.id === route.params.id || p.slug === route.params.id))
const images = computed(()=> product.value ? ([...(product.value.images || []), product.value.image].filter(Boolean).length ? [...new Set([...(product.value.images || []), product.value.image].filter(Boolean))] : [FALLBACK_IMAGE]) : [FALLBACK_IMAGE])
const related = computed(()=> store.products.filter((p)=> product.value && p.id !== product.value.id && (p.category === product.value.category || productBrand(p) === productBrand(product.value))).slice(0,4))
const whatsapp = computed(()=>`https://wa.me/923263972241?text=${encodeURIComponent(`Hi Haxon, please confirm fitment for ${product.value?.name || 'this product'}.`)}`)
</script>
<template><div class="min-h-screen bg-[#0B0D10] text-[#F5F5F2]"><section v-if="product" class="mx-auto max-w-7xl px-6 py-12"><router-link to="/products" class="text-[#A5A7AA]">← Back to collection</router-link><div class="mt-8 grid gap-10 lg:grid-cols-2"><div><div class="overflow-hidden rounded-[2.5rem] border border-white/10 bg-[#11151B]"><img :src="selected || images[0]" class="aspect-square w-full object-cover" @error="$event.target.src=FALLBACK_IMAGE" /></div><div class="mt-4 grid grid-cols-5 gap-3"><button v-for="image in images" :key="image" class="overflow-hidden rounded-2xl border border-white/10" @click="selected=image"><img :src="image" class="aspect-square object-cover" /></button></div></div><div class="self-center"><p class="text-xs uppercase tracking-[.35em] text-cyan-100/60">{{ productBrand(product) }} · {{ product.category }}</p><h1 class="mt-4 text-5xl font-black leading-none md:text-7xl">{{ product.name }}</h1><div class="mt-6 flex flex-wrap gap-2"><span class="rounded-full border border-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.16em]">{{ productMode(product) }}</span><span v-if="product.stock !== undefined" class="rounded-full border border-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.16em]">Stock {{ product.stock }}</span></div><p class="mt-6 text-4xl font-black">{{ formatPrice(product.salePrice || product.price) }}</p><p class="mt-6 text-lg leading-8 text-[#A5A7AA]">{{ product.description || 'Premium automotive accessory curated by Haxon Autostore.' }}</p><div class="mt-8 grid gap-3 sm:grid-cols-2"><button class="rounded-full bg-white px-6 py-4 font-bold uppercase tracking-[.16em] text-[#0B0D10]" @click="cart.addToCart(product)">Add to cart</button><a :href="whatsapp" target="_blank" class="rounded-full border border-white/10 px-6 py-4 text-center font-bold uppercase tracking-[.16em]">Confirm fitment</a></div><div class="mt-8 rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><h2 class="font-black">Fitment & specifications</h2><p class="mt-3 text-[#A5A7AA]">{{ product.fitmentNotes || product.compatibleVehicles || 'Please confirm vehicle year, variant, and trim before dispatch.' }}</p><pre class="mt-4 whitespace-pre-wrap text-sm text-[#A5A7AA]">{{ typeof product.specifications === 'object' ? JSON.stringify(product.specifications, null, 2) : (product.specifications || 'Specifications will be confirmed by Haxon support.') }}</pre></div></div></div><div v-if="related.length" class="mt-20"><h2 class="text-4xl font-black">Related products</h2><div class="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4"><ProductCard v-for="item in related" :key="item.id" :product="item" /></div></div></section><section v-else class="px-6 py-24 text-center"><h1 class="text-4xl font-black">Product not found</h1></section></div></template>
