<script setup>
import { ref } from 'vue'
import { collection, getDocs, query, where } from 'firebase/firestore'
import { db } from '../firebase/config'
import OrderStatusBadge from '../components/OrderStatusBadge.vue'
import { formatPrice, orderStatus, orderTotal, orderStatuses } from '../lib/catalog'
const orderNumber=ref(''); const phone=ref(''); const order=ref(null); const loading=ref(false); const error=ref('')
const track=async()=>{ loading.value=true; error.value=''; order.value=null; try{ const snap=await getDocs(query(collection(db,'orders'), where('orderNumber','==',orderNumber.value.trim()))); const found=snap.docs.map(d=>({id:d.id,...d.data()})).find(o=>(o.customer?.phone||o.phone||'').replace(/\s/g,'')===phone.value.replace(/\s/g,'')); if(found) order.value=found; else error.value='No order matched that order number and phone.' }catch(e){ error.value='Unable to check order right now.' } finally{ loading.value=false } }
</script>
<template><div class="min-h-screen bg-[#0B0D10] px-6 py-16 text-[#F5F5F2]"><div class="mx-auto max-w-4xl"><h1 class="text-5xl font-black">Track order.</h1><p class="mt-4 text-[#A5A7AA]">Enter your Haxon order number and phone number.</p><div class="mt-8 grid gap-3 rounded-[2rem] border border-white/10 bg-[#11151B] p-5 md:grid-cols-3"><input v-model="orderNumber" placeholder="HXN-2026-123456" class="rounded-2xl border border-white/10 bg-[#0B0D10] px-4 py-3"/><input v-model="phone" placeholder="03XX XXXXXXX" class="rounded-2xl border border-white/10 bg-[#0B0D10] px-4 py-3"/><button class="rounded-2xl bg-white px-5 py-3 font-bold text-[#0B0D10]" @click="track">{{ loading ? 'Checking...' : 'Track' }}</button></div><p v-if="error" class="mt-5 text-amber-200">{{ error }}</p><div v-if="order" class="mt-8 rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><div class="flex flex-wrap items-center justify-between gap-4"><h2 class="text-3xl font-black">{{ order.orderNumber }}</h2><OrderStatusBadge :status="orderStatus(order)" /></div><div class="mt-6 grid gap-3 md:grid-cols-4"><div v-for="status in orderStatuses" :key="status" class="rounded-2xl border p-4" :class="orderStatuses.indexOf(status) <= orderStatuses.indexOf(orderStatus(order)) ? 'border-cyan-100/40 bg-cyan-100/10' : 'border-white/10'"><p class="text-xs uppercase tracking-[.18em]">{{ status }}</p></div></div><div class="mt-6"><p class="font-bold">Total: {{ formatPrice(orderTotal(order)) }} · {{ order.paymentMethod }}</p><p class="mt-2 text-[#A5A7AA]">{{ (order.items || order.products || []).map(i => `${i.name} × ${i.quantity || 1}`).join(', ') }}</p></div></div></div></div></template>
