<script setup>
import { onMounted, onBeforeUnmount, ref } from 'vue'
const slides = [
  { eyebrow: 'Haxon Autostore', title: 'Drive components curated like a supercar studio.', word: 'HAXON', copy: 'Premium accessories, fitment-first ordering, and imported options composed for Pakistan’s detail-obsessed drivers.', cta: 'Shop collection', to: '/products' },
  { eyebrow: 'Fitment discipline', title: 'No random parts. Verified intent.', word: 'FITMENT', copy: 'Ready stock moves fast; confirmation products stay transparent until vehicle compatibility is checked.', cta: 'Track order', to: '/track-order' },
]
const active = ref(0); let timer; const go = (i) => { active.value = (i + slides.length) % slides.length }
onMounted(() => { timer = setInterval(() => go(active.value + 1), 5400) }); onBeforeUnmount(() => clearInterval(timer))
</script>
<template><section class="relative min-h-[92vh] overflow-hidden bg-[#07090d] text-[#F5F5F2]"><div class="absolute inset-0 bg-[radial-gradient(circle_at_72%_38%,rgba(220,38,38,.25),transparent_25%),linear-gradient(110deg,#05070a_0%,#10141b_48%,#24272b_100%)]"></div><div class="absolute right-[-8vw] top-[12vh] h-[55vh] w-[68vw] rounded-l-full border border-white/10 bg-[linear-gradient(135deg,rgba(255,255,255,.14),rgba(255,255,255,.02))] shadow-2xl shadow-black/60 backdrop-blur-sm"></div><div class="absolute bottom-16 right-10 hidden w-[46vw] border-t border-white/20 pt-6 lg:block"><div class="h-2 rounded-full bg-gradient-to-r from-white via-red-500 to-transparent"></div><div class="mt-7 grid grid-cols-3 gap-4 text-xs uppercase tracking-[.22em] text-white/50"><span>Ready Dispatch</span><span>Fitment Checked</span><span>Premium Imports</span></div></div><div class="relative z-10 mx-auto flex min-h-[92vh] max-w-7xl items-center px-6 py-24"><div class="max-w-4xl"><p class="text-xs font-black uppercase tracking-[.5em] text-red-300/80">{{ slides[active].eyebrow }}</p><p class="pointer-events-none mt-5 text-[17vw] font-black leading-none tracking-[-.11em] text-white/[.035]">{{ slides[active].word }}</p><h1 class="-mt-[8vw] text-5xl font-black leading-[.9] tracking-[-.07em] md:text-7xl lg:text-8xl">{{ slides[active].title }}</h1><p class="mt-7 max-w-2xl text-lg leading-8 text-white/60">{{ slides[active].copy }}</p><div class="mt-10 flex flex-wrap gap-3"><router-link :to="slides[active].to" class="rounded-full bg-white px-8 py-4 text-xs font-black uppercase tracking-[.22em] text-black">{{ slides[active].cta }}</router-link><router-link to="/contact" class="rounded-full border border-white/15 px-8 py-4 text-xs font-black uppercase tracking-[.22em]">Fitment concierge</router-link></div></div></div><div class="absolute bottom-8 left-1/2 z-20 flex -translate-x-1/2 gap-3"><button v-for="(_, i) in slides" :key="i" class="h-1.5 rounded-full transition-all" :class="i === active ? 'w-12 bg-white' : 'w-6 bg-white/25'" @click="go(i)"></button></div></section></template>
