<script setup>
import { toast } from 'vue-sonner'
import { ref, computed, watch } from 'vue'
import { uploadProductImage, uploadProductImages } from '../../services/imageService'
import { createProduct } from '../../services/productService'
import { slugify, formatPrice } from '../../lib/catalog'

const categories = ['Exterior Accessories','Interior Accessories','LED & Lighting','Android Panels','Audio & Multimedia','Speakers','Car Care','Security','Emergency Tools','Phone Holders','Charging Accessories','Air Pumps','Seat Covers','Tools','Other']
const statusOptions = ['draft', 'published', 'archived']
const compatibilityTypes = ['universal', 'brand-specific', 'multiple']
const form = ref({ name:'', slug:'', sku:'', category:'', brand:'', status:'published', active:true, featured:false, sortOrder:0, price:'', saleEnabled:false, salePrice:'', compareAtPrice:'', currency:'PKR', stock:0, availability:'Available', estimatedDelivery:'2-3 Days', compatibilityType:'universal', compatibleMakes:'', compatibleModels:'', compatibleYears:'', compatibleVariants:'', mainImage:'', thumbnailImage:'', bannerImage:'', galleryImages:[], shortDescription:'', description:'', features:'', specifications:[{ label:'', value:'' }], fitmentNotes:'', installationNotes:'', packageContents:'', warranty:'', shippingInformation:'', downloads:[{ label:'', url:'' }], youtubeVideo:'', faqs:[{ question:'', answer:'' }], seoTitle:'', seoDescription:'', mainImagePath:'', thumbnailImagePath:'', bannerImagePath:'', galleryImagePaths:[] })
const files = ref({ main:null, thumbnail:null, banner:null, gallery:[] })
const previews = ref({ main:'', thumbnail:'', banner:'', gallery:[] })
const loading = ref(false)
watch(() => form.value.name, (value) => { if (!form.value.slug) form.value.slug = slugify(value) })
const currentPrice = computed(() => Number(form.value.saleEnabled ? form.value.salePrice : form.value.price) || 0)
const discount = computed(() => form.value.compareAtPrice && Number(form.value.compareAtPrice) > currentPrice.value ? Math.round(((Number(form.value.compareAtPrice) - currentPrice.value) / Number(form.value.compareAtPrice)) * 100) : 0)
const setFile = (key, event) => { const file = event.target.files?.[0]; if (!file) return; files.value[key] = file; previews.value[key] = URL.createObjectURL(file) }
const setGallery = (event) => { files.value.gallery = [...event.target.files].slice(0, 12); previews.value.gallery = files.value.gallery.map((file) => URL.createObjectURL(file)) }
const moveGallery = (index, dir) => { const next = [...form.value.galleryImages]; const target = index + dir; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; form.value.galleryImages = next }
const removeGallery = (index) => { form.value.galleryImages = form.value.galleryImages.filter((_, i) => i !== index); form.value.galleryImagePaths = form.value.galleryImagePaths.filter((_, i) => i !== index) }
const addRow = (key, row) => form.value[key].push(row)
const removeRow = (key, index) => { form.value[key].splice(index, 1) }
const uploadAll = async () => {
  if (files.value.main) { const uploaded = await uploadProductImage(files.value.main, 'products/main'); form.value.mainImage = uploaded.url; form.value.mainImagePath = uploaded.path }
  if (files.value.thumbnail) { const uploaded = await uploadProductImage(files.value.thumbnail, 'products/thumbnails'); form.value.thumbnailImage = uploaded.url; form.value.thumbnailImagePath = uploaded.path }
  if (files.value.banner) { const uploaded = await uploadProductImage(files.value.banner, 'products/banners'); form.value.bannerImage = uploaded.url; form.value.bannerImagePath = uploaded.path }
  if (files.value.gallery.length) { const uploaded = await uploadProductImages(files.value.gallery); form.value.galleryImages = [...form.value.galleryImages, ...uploaded.map((item) => item.url)].slice(0, 12); form.value.galleryImagePaths = [...form.value.galleryImagePaths, ...uploaded.map((item) => item.path)].slice(0, 12) }
}
const saveProduct = async () => { try { loading.value = true; await uploadAll(); await createProduct(form.value); toast.success('Product created successfully.') } catch (err) { toast.error(err.message || 'Failed to save product.') } finally { loading.value = false } }
</script>
<template>
  <div class="admin-shell"><div class="admin-page">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8"><div><h1 class="admin-title">Add Product</h1><p class="admin-muted mt-3">Create a production-ready CMS product without changing the storefront design.</p></div><router-link to="/admin/products" class="admin-btn-secondary">Back</router-link></div>
    <div class="grid grid-cols-1 xl:grid-cols-3 gap-8"><div class="xl:col-span-2 space-y-6">
      <details open class="admin-card p-6"><summary class="admin-section-title cursor-pointer">General</summary><div class="grid md:grid-cols-2 gap-4 mt-5"><input v-model="form.name" class="admin-input" placeholder="Name *"><input v-model="form.slug" class="admin-input" placeholder="Slug *"><input v-model="form.sku" class="admin-input" placeholder="SKU"><select v-model="form.category" class="admin-input"><option value="">Category</option><option v-for="c in categories" :key="c">{{ c }}</option></select><input v-model="form.brand" class="admin-input" placeholder="Product brand / manufacturer"><select v-model="form.status" class="admin-input"><option v-for="s in statusOptions" :key="s">{{ s }}</option></select><input v-model.number="form.sortOrder" type="number" class="admin-input" placeholder="Sort order"><div class="flex gap-6 text-white"><label><input v-model="form.active" type="checkbox"> Active</label><label><input v-model="form.featured" type="checkbox"> Featured</label></div></div></details>
      <details open class="admin-card p-6"><summary class="admin-section-title cursor-pointer">Images</summary><div class="grid md:grid-cols-2 gap-4 mt-5"><input v-model="form.mainImage" class="admin-input" placeholder="Main image URL *"><input type="file" class="admin-input" @change="setFile('main',$event)"><input v-model="form.thumbnailImage" class="admin-input" placeholder="Thumbnail URL"><input type="file" class="admin-input" @change="setFile('thumbnail',$event)"><input v-model="form.bannerImage" class="admin-input" placeholder="Banner URL"><input type="file" class="admin-input" @change="setFile('banner',$event)"></div></details>
      <details open class="admin-card p-6"><summary class="admin-section-title cursor-pointer">Pricing</summary><div class="grid md:grid-cols-3 gap-4 mt-5"><input v-model="form.price" type="number" class="admin-input" placeholder="Price *"><input v-model="form.compareAtPrice" type="number" class="admin-input" placeholder="Compare at price"><input v-model="form.currency" class="admin-input" placeholder="Currency"><label class="text-white"><input v-model="form.saleEnabled" type="checkbox"> Sale enabled</label><input v-model="form.salePrice" type="number" class="admin-input" placeholder="Sale price"><input v-model="form.stock" type="number" class="admin-input" placeholder="Stock"></div></details>
      <details class="admin-card p-6"><summary class="admin-section-title cursor-pointer">Compatibility</summary><div class="grid md:grid-cols-2 gap-4 mt-5"><select v-model="form.compatibilityType" class="admin-input"><option v-for="t in compatibilityTypes" :key="t">{{ t }}</option></select><input v-model="form.compatibleMakes" class="admin-input" placeholder="Makes, one per line or comma"><textarea v-model="form.compatibleModels" class="admin-input" placeholder="Models"></textarea><textarea v-model="form.compatibleYears" class="admin-input" placeholder="Years"></textarea><textarea v-model="form.compatibleVariants" class="admin-input" placeholder="Variants"></textarea><textarea v-model="form.fitmentNotes" class="admin-input" placeholder="Fitment notes"></textarea></div></details>
      <details class="admin-card p-6"><summary class="admin-section-title cursor-pointer">Descriptions</summary><textarea v-model="form.shortDescription" class="admin-input mt-5" placeholder="Short description"></textarea><textarea v-model="form.description" rows="6" class="admin-input mt-4" placeholder="Full description"></textarea><textarea v-model="form.features" class="admin-input mt-4" placeholder="Features, one per line"></textarea></details>
      <details class="admin-card p-6"><summary class="admin-section-title cursor-pointer">Specifications</summary><div v-for="(row,i) in form.specifications" :key="i" class="grid grid-cols-[1fr_1fr_auto] gap-3 mt-4"><input v-model="row.label" class="admin-input" placeholder="Power"><input v-model="row.value" class="admin-input" placeholder="60W"><button class="admin-btn-secondary" @click="removeRow('specifications',i)">Delete</button></div><button class="admin-btn-secondary mt-4" @click="addRow('specifications',{label:'',value:''})">Add specification</button></details>
      <details class="admin-card p-6"><summary class="admin-section-title cursor-pointer">Gallery</summary><input type="file" multiple class="admin-input mt-5" @change="setGallery"><input v-model="form.galleryImages" class="admin-input mt-4" placeholder="External gallery URLs"><div class="grid grid-cols-3 gap-3 mt-4"><div v-for="(image,i) in form.galleryImages" :key="image" class="bg-white/5 p-2"><img :src="image" class="h-24 w-full object-cover"><button @click="moveGallery(i,-1)">↑</button><button @click="moveGallery(i,1)">↓</button><button @click="removeGallery(i)">×</button></div></div></details>
      <details class="admin-card p-6"><summary class="admin-section-title cursor-pointer">Shipping</summary><div class="grid md:grid-cols-2 gap-4 mt-5"><input v-model="form.estimatedDelivery" class="admin-input" placeholder="Estimated delivery"><textarea v-model="form.shippingInformation" class="admin-input" placeholder="Shipping information"></textarea><textarea v-model="form.installationNotes" class="admin-input" placeholder="Installation notes"></textarea><input v-model="form.warranty" class="admin-input" placeholder="Warranty"><textarea v-model="form.packageContents" class="admin-input" placeholder="Package contents"></textarea></div></details>
      <details class="admin-card p-6"><summary class="admin-section-title cursor-pointer">SEO & Detail Content</summary><input v-model="form.seoTitle" class="admin-input mt-5" placeholder="SEO title"><textarea v-model="form.seoDescription" class="admin-input mt-4" placeholder="SEO description"></textarea><input v-model="form.youtubeVideo" class="admin-input mt-4" placeholder="YouTube video URL"><div v-for="(row,i) in form.downloads" :key="`d-${i}`" class="grid grid-cols-[1fr_1fr_auto] gap-3 mt-4"><input v-model="row.label" class="admin-input" placeholder="Download label"><input v-model="row.url" class="admin-input" placeholder="URL"><button class="admin-btn-secondary" @click="removeRow('downloads',i)">Delete</button></div><button class="admin-btn-secondary mt-4" @click="addRow('downloads',{label:'',url:''})">Add download</button><div v-for="(row,i) in form.faqs" :key="`f-${i}`" class="grid grid-cols-[1fr_1fr_auto] gap-3 mt-4"><input v-model="row.question" class="admin-input" placeholder="Question"><input v-model="row.answer" class="admin-input" placeholder="Answer"><button class="admin-btn-secondary" @click="removeRow('faqs',i)">Delete</button></div><button class="admin-btn-secondary mt-4" @click="addRow('faqs',{question:'',answer:''})">Add FAQ</button></details>
    </div><aside class="space-y-6"><div class="admin-card p-6"><h2 class="admin-section-title mb-4">Preview</h2><img v-if="previews.main || form.mainImage" :src="previews.main || form.mainImage" class="h-72 w-full object-cover rounded-xl"><h3 class="text-white text-xl font-black mt-4">{{ form.name || 'Product name' }}</h3><p class="text-slate-400">{{ form.brand || 'Brand' }}</p><p class="text-red-300 font-black">{{ formatPrice(currentPrice, form.currency) }}</p><p v-if="discount" class="text-green-400">{{ discount }}% off</p></div><button @click="saveProduct" :disabled="loading" class="admin-btn-primary w-full py-4">{{ loading ? 'Saving...' : 'Save Product' }}</button></aside></div>
  </div></div>
</template>
