<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { toast } from 'vue-sonner'
import { getContentDoc, listContent, saveContent, deleteContent, saveSiteSettings, saveSignatureShowcase } from '../../lib/contentService'
import { fallbackSiteSettings, fallbackSignatureShowcase } from '../../lib/contentFallbacks'
import { uploadContentImage } from '../../lib/storageService'

const managers = [
  { key: 'heroSlides', title: 'Hero Slides', imageField: 'image', fields: ['eyebrow','title','subtitle','backgroundWord','image','imageAlt','primaryCtaLabel','primaryCtaLink','secondaryCtaLabel','secondaryCtaLink','statOneLabel','statOneValue','statTwoLabel','statTwoValue','statThreeLabel','statThreeValue','sortOrder','active'] },
  { key: 'categoryTiles', title: 'Homepage Categories', imageField: 'image', fields: ['title','slug','description','image','imageAlt','link','size','sortOrder','active'] },
  { key: 'cars', title: 'Cars', imageField: 'thumbnail', fields: ['manufacturer','model','slug','heroImage','thumbnail','yearRange','featured','sortOrder','active','description','seoTitle','seoDescription','ogImage','canonicalUrl'] },
  { key: 'categories', title: 'Categories', imageField: 'image', fields: ['name','slug','image','description','icon','featured','active','sortOrder','link','externalUrl'] },
  { key: 'pages', title: 'About Page', fields: ['title','slug','heroEyebrow','heroTitle','heroSubtitle','sectionOneTitle','sectionOneBody','quote','ctaTitle','ctaLabel','ctaLink','sortOrder','active'] },
  { key: 'brandTiles', title: 'Homepage Featured Cars' , imageField: 'image', fields: ['name','slug','logo','image','description','link','sortOrder','active'] },
  { key: 'brands', title: 'Product Brands', imageField: 'image', fields: ['name','slug','logo','bannerImage','image','description','website','featured','sortOrder','active'] },
  { key: 'catalogs', title: 'Catalogs', imageField: 'thumbnail', fields: ['name','slug','brand','category','thumbnail','pdfUrl','description','sortOrder','active'] },
  { key: 'trustItems', title: 'Trust Items', fields: ['title','description','icon','sortOrder','active'] },
]
const active = ref('heroSlides'); const loading = ref(false); const saving = ref(false); const uploadProgress = ref(0); const rows = reactive({ heroSlides: [], categoryTiles: [], brandTiles: [], brands: [], catalogs: [], trustItems: [], cars: [], categories: [], pages: [] })
const form = ref({ active: true, sortOrder: 1 }); const editingId = ref(null); const settings = ref({ ...fallbackSiteSettings }); const signature = ref({ ...fallbackSignatureShowcase })
const current = () => managers.find((m) => m.key === active.value)
const load = async () => { loading.value = true; try { const [site, showcase] = await Promise.all([getContentDoc('siteSettings', 'general'), getContentDoc('signatureShowcase', 'main')]); if (site) settings.value = { ...fallbackSiteSettings, ...site }; if (showcase) signature.value = { ...fallbackSignatureShowcase, ...showcase }; await Promise.all(managers.map(async (m) => { rows[m.key] = await listContent(m.key) })) } catch(e){ toast.error(e.message || 'Unable to load content') } finally { loading.value = false } }
const edit = (row) => { editingId.value = row.id; form.value = { active: true, sortOrder: 1, ...row } }
const reset = () => { editingId.value = null; form.value = { active: true, sortOrder: rows[active.value]?.length + 1 || 1 } }
const normalizeSavePayload = () => active.value === 'pages' ? {
  title: form.value.title || 'About Page',
  slug: form.value.slug || 'about',
  hero: { eyebrow: form.value.heroEyebrow, title: form.value.heroTitle || form.value.title, subtitle: form.value.heroSubtitle, backgroundWord: 'MANIFESTO' },
  sections: [
    { id: 'manifesto', type: 'manifesto', eyebrow: 'The philosophy', title: form.value.sectionOneTitle, body: form.value.sectionOneBody, sortOrder: 1, active: true },
    { id: 'quote', type: 'quote', quote: form.value.quote, attribution: 'Haxon', sortOrder: 2, active: Boolean(form.value.quote) },
  ],
  cta: { title: form.value.ctaTitle, label: form.value.ctaLabel, link: form.value.ctaLink, active: true },
  active: form.value.active !== false,
  sortOrder: Number(form.value.sortOrder || 1),
} : form.value
const save = async () => { if (!form.value.title && !form.value.name && !form.value.model) return toast.error('Title, name, or model is required'); saving.value = true; try { await saveContent(active.value, normalizeSavePayload(), active.value === 'pages' ? 'about' : editingId.value); toast.success(editingId.value ? 'Content updated' : 'Content created'); reset(); await load() } catch(e){ toast.error(e.message || 'Save failed') } finally { saving.value = false } }
const remove = async (row) => { if (!confirm(`Delete ${row.title || row.name || row.model}?`)) return; try { await deleteContent(active.value, row.id); toast.success('Content deleted'); await load() } catch(e){ toast.error('Delete failed') } }
const archive = async (row) => { try { await saveContent(active.value, { active: false }, row.id); toast.success('Content archived'); await load() } catch(e){ toast.error('Archive failed') } }
const upload = async (event, target = form.value, field = current()?.imageField || 'image') => { const file = event.target.files?.[0]; if (!file) return; uploadProgress.value = 0; try { const image = await uploadContentImage(file, active.value, { onProgress: (value) => { uploadProgress.value = value } }); target[field] = image.url; if (field === 'pdfUrl') target.pdfPath = image.path; else target[`${field}Path`] = image.path; toast.success('File uploaded') } catch(e){ toast.error(e.message || 'Upload failed') } finally { event.target.value = ''; setTimeout(() => { uploadProgress.value = 0 }, 1200) } }
const saveSettings = async () => { try { await saveSiteSettings(settings.value); toast.success('General settings saved') } catch(e){ toast.error('Settings save failed') } }
const saveSignature = async () => { try { await saveSignatureShowcase(signature.value); toast.success('Signature showcase saved') } catch(e){ toast.error('Signature save failed') } }
watch(active, reset)
onMounted(load)
</script>
<template>
  <div class="admin-shell"><div class="admin-page pt-28">
    <div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p class="admin-eyebrow">Storefront control</p><h1 class="admin-title">Content manager</h1><p class="admin-muted mt-3">Manage homepage Firestore content. Storefront keeps curated fallbacks if documents are missing.</p></div><router-link to="/admin" class="admin-btn-secondary">Dashboard</router-link></div>
    <div class="mt-8 grid gap-4 md:grid-cols-3 lg:grid-cols-6"><button v-for="m in managers" :key="m.key" class="admin-card p-5 text-left transition hover:border-white/25" :class="active===m.key && 'border-red-400/50 bg-red-500/10'" @click="active=m.key; reset()"><b>{{ m.title }}</b><p class="admin-muted mt-2 text-sm">{{ rows[m.key].length }} records</p></button><button class="admin-card p-5 text-left" @click="active='signature'"><b>Signature Showcase</b><p class="admin-muted mt-2 text-sm">Single feature</p></button><button class="admin-card p-5 text-left" @click="active='settings'"><b>General Settings</b><p class="admin-muted mt-2 text-sm">Brand/footer</p></button></div>

    <section v-if="managers.some(m=>m.key===active)" class="mt-8 grid gap-6 lg:grid-cols-[1fr_.9fr]"><div class="admin-card p-6"><div class="flex items-center justify-between"><h2 class="admin-section-title">{{ current().title }}</h2><button class="admin-btn-primary" @click="reset">Add new</button></div><div v-if="loading" class="admin-card-soft mt-5 p-8 text-center admin-muted">Loading...</div><div v-else-if="!rows[active].length" class="admin-card-soft mt-5 p-8 text-center admin-muted">No Firestore records yet. Fallback content remains live.</div><div v-else class="admin-table-wrap mt-5"><table class="admin-table"><thead><tr><th>Preview</th><th>Title</th><th>Sort</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="row in rows[active]" :key="row.id"><td><img v-if="row.image || row.logo || row.thumbnail || row.heroImage" :src="row.image || row.logo || row.thumbnail || row.heroImage" class="h-12 w-16 rounded-xl object-cover" /></td><td><b>{{ row.title || row.name || row.model }}</b><p class="admin-muted text-xs">{{ row.description || row.subtitle }}</p></td><td>{{ row.sortOrder }}</td><td><span class="rounded-full px-3 py-1 text-xs" :class="row.active!==false ? 'bg-emerald-400/15 text-emerald-200' : 'bg-white/10 text-white/50'">{{ row.active!==false ? 'Active' : 'Inactive' }}</span></td><td class="space-x-2"><button class="admin-btn-secondary !px-3 !py-2" @click="edit(row)">Edit</button><button class="admin-btn-secondary !px-3 !py-2" @click="archive(row)">Archive</button><button class="admin-btn-secondary !px-3 !py-2" @click="remove(row)">Delete</button></td></tr></tbody></table></div></div>
      <form class="admin-card p-6" @submit.prevent="save"><h2 class="admin-section-title">{{ editingId ? 'Edit' : 'Add' }} {{ current().title }}</h2><div class="mt-5 grid gap-4"><label v-for="field in current().fields" :key="field" class="block"><span class="admin-label">{{ field }}</span><input v-if="field==='active'" v-model="form[field]" type="checkbox" class="h-5 w-5"><input v-else-if="field==='sortOrder'" v-model.number="form[field]" type="number" class="admin-input"><textarea v-else-if="field==='subtitle'||field==='description'" v-model="form[field]" class="admin-input min-h-24"></textarea><input v-else v-model="form[field]" class="admin-input"></label><label v-if="current().imageField" class="block"><span class="admin-label">Upload image</span><input type="file" accept="image/*" class="admin-input" @change="upload($event, form, current().imageField)"></label><label v-if="active==='catalogs'" class="block"><span class="admin-label">Upload PDF</span><input type="file" accept="application/pdf" class="admin-input" @change="upload($event, form, 'pdfUrl')"></label><p v-if="uploadProgress" class="admin-muted text-sm">Upload {{ uploadProgress }}%</p><img v-if="form.image || form.thumbnail || form.logo || form.heroImage" :src="form.image || form.thumbnail || form.logo || form.heroImage" class="h-40 rounded-2xl object-cover"></div><button class="admin-btn-primary mt-6 w-full" :disabled="saving">{{ saving ? 'Saving...' : 'Save content' }}</button></form></section>

    <section v-else-if="active==='settings'" class="admin-card mt-8 p-6"><h2 class="admin-section-title">General settings</h2><div class="mt-5 grid gap-4 md:grid-cols-2"><label v-for="(_, field) in settings" :key="field"><span class="admin-label">{{ field }}</span><textarea v-if="field.includes('Statement')" v-model="settings[field]" class="admin-input"></textarea><input v-else v-model="settings[field]" class="admin-input"></label></div><button class="admin-btn-primary mt-6" @click="saveSettings">Save settings</button></section>
    <section v-else class="admin-card mt-8 p-6"><h2 class="admin-section-title">Signature showcase</h2><div class="mt-5 grid gap-4 md:grid-cols-2"><label v-for="(_, field) in signature" :key="field"><span class="admin-label">{{ field }}</span><textarea v-if="['subtitle'].includes(field)" v-model="signature[field]" class="admin-input"></textarea><input v-else-if="field==='active'" v-model="signature[field]" type="checkbox" class="h-5 w-5"><input v-else v-model="signature[field]" class="admin-input"></label><input type="file" accept="image/*" class="admin-input" @change="upload($event, signature, 'image')"><p v-if="uploadProgress" class="admin-muted text-sm">Upload {{ uploadProgress }}%</p></div><button class="admin-btn-primary mt-6" @click="saveSignature">Save signature</button></section>
  </div></div>
</template>
