<script setup>
import { computed, onMounted, ref } from 'vue'
import { collection, getDocs, doc, updateDoc, query, orderBy, serverTimestamp } from 'firebase/firestore'
import { db } from '../../firebase/config'
import { buildTimelineEntry, formatPrice, orderStatus, orderTotal, orderStatuses, normalizePaymentStatus } from '../../lib/catalog'
import OrderStatusBadge from '../../components/OrderStatusBadge.vue'

const orders = ref([]); const loading = ref(true); const error = ref(''); const search = ref(''); const selectedStatus = ref(''); const updatingOrderId = ref('')
const formatDate = (timestamp) => timestamp?.toDate?.()?.toLocaleString('en-PK', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) || 'No date'
const getOrderItems = (order) => order.items || order.products || []
const fetchOrders = async () => { loading.value = true; error.value = ''; try { const snap = await getDocs(query(collection(db, 'orders'), orderBy('createdAt', 'desc'))); orders.value = snap.docs.map((d) => ({ id: d.id, ...d.data() })) } catch (err) { console.error(err); error.value = 'Failed to load orders.' } finally { loading.value = false } }
const filteredOrders = computed(() => { const term = search.value.toLowerCase().trim(); return orders.value.filter((order) => { const text = [order.customer?.name, order.customerName, order.customer?.phone, order.phone, order.customer?.city, order.city, order.orderNumber, order.id, orderStatus(order), normalizePaymentStatus(order.paymentStatus)].join(' ').toLowerCase(); return (!term || text.includes(term)) && (!selectedStatus.value || orderStatus(order) === selectedStatus.value) }) })
const stats = computed(() => ({ total: orders.value.length, pending: orders.value.filter((o) => orderStatus(o) === 'Pending').length, delivered: orders.value.filter((o) => orderStatus(o) === 'Delivered').length, cancelled: orders.value.filter((o) => orderStatus(o) === 'Cancelled').length, revenue: orders.value.filter((o) => orderStatus(o) === 'Delivered').reduce((sum, o) => sum + orderTotal(o), 0) }))
const updateStatus = async (order, status) => { updatingOrderId.value = order.id; error.value = ''; try { const timeline = [...(order.timeline || []), buildTimelineEntry(status, `Admin updated status from ${orderStatus(order)} to ${status}`)]; await updateDoc(doc(db, 'orders', order.id), { orderStatus: status, status, timeline, updatedAt: serverTimestamp() }); orders.value = orders.value.map((o) => (o.id === order.id ? { ...o, orderStatus: status, status, timeline } : o)) } catch (err) { console.error(err); error.value = 'Failed to update order status.' } finally { updatingOrderId.value = '' } }
const clearFilters = () => { search.value = ''; selectedStatus.value = '' }
onMounted(fetchOrders)
</script>
<template>
  <div class="min-h-screen bg-[#07090d] px-6 py-8 text-white"><div class="mx-auto max-w-7xl">
    <div class="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p class="text-xs uppercase tracking-[.35em] text-white/40">Haxon control</p><h1 class="mt-2 text-5xl font-black tracking-[-.04em]">Orders</h1><p class="mt-2 text-white/50">Manage confirmation, payment visibility, dispatch and delivery from one source of truth.</p></div><button @click="fetchOrders" class="rounded-full border border-white/10 px-5 py-3 font-bold hover:bg-white hover:text-black">Refresh</button></div>
    <div class="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-5"><div v-for="(value,label) in stats" :key="label" class="rounded-[1.5rem] border border-white/10 bg-white/[.04] p-5"><p class="text-sm capitalize text-white/45">{{ label }}</p><h2 class="mt-2 text-3xl font-black">{{ label === 'revenue' ? formatPrice(value) : value }}</h2></div></div>
    <div class="mb-8 rounded-[2rem] border border-white/10 bg-white/[.04] p-5"><div class="grid gap-4 md:grid-cols-3"><input v-model="search" placeholder="Search customer, phone, city, order number..." class="input md:col-span-2"/><select v-model="selectedStatus" class="input"><option value="">All statuses</option><option v-for="status in orderStatuses" :key="status">{{ status }}</option></select></div><div class="mt-4 flex justify-between text-sm text-white/45"><p>Showing {{ filteredOrders.length }} of {{ orders.length }}</p><button @click="clearFilters" class="hover:text-white">Clear filters</button></div></div>
    <div v-if="loading" class="rounded-[2rem] border border-white/10 p-10">Loading orders...</div><div v-else-if="error" class="rounded-[2rem] border border-red-400/30 bg-red-400/10 p-6 text-red-100">{{ error }}</div><div v-else-if="!filteredOrders.length" class="rounded-[2rem] border border-white/10 p-12 text-center"><h2 class="text-3xl font-black">No orders found</h2><button @click="clearFilters" class="mt-6 rounded-full bg-white px-6 py-3 font-bold text-black">Clear filters</button></div>
    <div v-else class="space-y-5"><article v-for="order in filteredOrders" :key="order.id" class="rounded-[2rem] border border-white/10 bg-white/[.04] p-6"><div class="grid gap-5 lg:grid-cols-[1fr_18rem]"><div><div class="flex flex-wrap items-center gap-3"><h2 class="text-2xl font-black">{{ order.customer?.name || order.customerName || 'Unnamed Customer' }}</h2><OrderStatusBadge :status="orderStatus(order)" /><span class="rounded-full border border-white/10 px-3 py-1 text-xs">Payment: {{ normalizePaymentStatus(order.paymentStatus) }}</span></div><div class="mt-4 grid gap-2 text-sm text-white/55 md:grid-cols-2"><p>Order: {{ order.orderNumber || order.id }}</p><p>Date: {{ formatDate(order.createdAt) }}</p><p>Phone: {{ order.customer?.phone || order.phone || '-' }}</p><p>City: {{ order.customer?.city || order.city || '-' }}</p><p>Payment method: {{ order.paymentMethod || 'Not selected' }}</p><p>Items: {{ getOrderItems(order).length }}</p></div></div><div class="space-y-3"><select :value="orderStatus(order)" :disabled="updatingOrderId === order.id" class="input" @change="updateStatus(order, $event.target.value)"><option v-for="status in orderStatuses" :key="status">{{ status }}</option></select><p v-if="updatingOrderId === order.id" class="text-sm text-white/45">Saving to Firestore...</p><div class="rounded-2xl border border-white/10 p-4"><p class="text-sm text-white/45">Total</p><h3 class="mt-1 text-2xl font-black">{{ formatPrice(orderTotal(order)) }}</h3></div><router-link :to="`/admin/orders/${order.id}`" class="block rounded-full bg-white py-3 text-center font-black uppercase tracking-[.16em] text-black">Details</router-link></div></div></article></div>
  </div></div>
</template>
<style scoped>.input{width:100%;border-radius:1rem;border:1px solid rgba(255,255,255,.1);background:#05070a;padding:1rem;color:white;outline:none}.input:focus{border-color:rgba(255,255,255,.35)}</style>
