<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { doc, getDoc, updateDoc, serverTimestamp } from 'firebase/firestore'
import { db } from '../../firebase/config'
import { formatPrice, orderStatus, orderTotal, orderStatuses, paymentStatuses } from '../../lib/catalog'
import OrderStatusBadge from '../../components/OrderStatusBadge.vue'
const route=useRoute(); const order=ref(null); const form=ref({ orderStatus:'Pending', paymentStatus:'Unpaid', deliveryCharges:0, customAdjustment:0, adminNotes:'' })
const load=async()=>{ const snap=await getDoc(doc(db,'orders',route.params.id)); if(snap.exists()){ order.value={id:snap.id,...snap.data()}; form.value={ orderStatus:orderStatus(order.value), paymentStatus:order.value.paymentStatus||'Unpaid', deliveryCharges:Number(order.value.deliveryCharges||order.value.delivery||0), customAdjustment:Number(order.value.customAdjustment||0), adminNotes:order.value.adminNotes||'' } } }
const save=async()=>{ const total=Number(order.value.subtotal||0)+Number(form.value.deliveryCharges||0)+Number(form.value.customAdjustment||0)-Number(order.value.discount||0); await updateDoc(doc(db,'orders',order.value.id),{ ...form.value, status:form.value.orderStatus, total, totalAmount:total, updatedAt:serverTimestamp(), timeline:[...(order.value.timeline||[]),{status:form.value.orderStatus,label:`Admin updated to ${form.value.orderStatus}`,at:new Date().toISOString()}] }); await load() }
onMounted(load)
</script>
<template><div class="min-h-screen bg-gray-950 px-6 py-10 text-white"><div v-if="order" class="mx-auto max-w-5xl"><router-link to="/admin/orders" class="text-gray-400">← Orders</router-link><div class="mt-6 rounded-3xl border border-white/10 bg-white/[.04] p-6"><div class="flex flex-wrap justify-between gap-4"><div><h1 class="text-4xl font-black">{{ order.orderNumber || order.id }}</h1><p class="mt-2 text-gray-400">{{ order.customer?.name || order.customerName }} · {{ order.customer?.phone || order.phone }}</p></div><OrderStatusBadge :status="orderStatus(order)" /></div><div class="mt-8 grid gap-4 md:grid-cols-2"><select v-model="form.orderStatus" class="input"><option v-for="s in orderStatuses" :key="s">{{ s }}</option></select><select v-model="form.paymentStatus" class="input"><option v-for="s in paymentStatuses" :key="s">{{ s }}</option></select><input v-model.number="form.deliveryCharges" type="number" class="input" placeholder="Delivery charges"/><input v-model.number="form.customAdjustment" type="number" class="input" placeholder="Custom adjustment"/><textarea v-model="form.adminNotes" class="input md:col-span-2" placeholder="Internal admin notes"></textarea></div><button class="mt-5 rounded-full bg-white px-6 py-3 font-bold text-black" @click="save">Save order updates</button></div><div class="mt-6 rounded-3xl border border-white/10 p-6"><h2 class="text-2xl font-black">Items · {{ formatPrice(orderTotal(order)) }}</h2><div v-for="item in (order.items || order.products || [])" :key="item.id || item.name" class="mt-4 flex justify-between border-t border-white/10 pt-4"><span>{{ item.name }} × {{ item.quantity || 1 }}</span><b>{{ formatPrice(Number(item.price||0) * Number(item.quantity||1)) }}</b></div></div></div></div></template>
<style scoped>.input{border-radius:1rem;border:1px solid rgba(255,255,255,.1);background:#020617;padding:1rem;color:white}</style>
